[project]
name = "auto-update"
version = "0.1.0"
description = "Auto-update docker-compose.images.yml"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
