name: Auto Update Docker Compose File
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  auto-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Add GOBIN to PATH
        run: |
          gobin=$(go env GOBIN)
          if [ -z "$gobin" ]; then
            gobin=$(go env GOPATH)/bin
          fi
          echo "GOBIN=$gobin" >> $GITHUB_ENV
          echo "$gobin" >> $GITHUB_PATH
        shell: bash
      - name: Install yamlfmt
        run: |
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
          # Verify installation
          command -v yamlfmt || { echo "yamlfmt command still not found after install"; exit 1; }
          yamlfmt --version
        shell: bash
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
      - name: Run auto-update script
        working-directory: .github/workflows/scripts/auto-update
        run: uv run main.py
      - name: Move Docker Compose file
        run: |
          mv .github/workflows/scripts/auto-update/docker-compose.images.yml ec2-docker-compose/
      - name: Format Docker Compose file
        run: |
          yamlfmt ec2-docker-compose/docker-compose.images.yml
        shell: bash
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ec2-docker-compose/docker-compose.images.yml
          git commit -am "chore: auto update docker-compose.images.yml" || echo "We're good for now. See you next time!"
          git pull --rebase
          git push